version: "3.9"

services:
  postgres:
    image: hub.iot-home.cn/library/postgres:16-alpine
    container_name: trendinghub-postgres
    environment:
      POSTGRES_USER: trendinghub
      POSTGRES_PASSWORD: trendinghub
      POSTGRES_DB: trendinghub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: hub.iot-home.cn/library/redis:7-alpine
    container_name: trendinghub-redis
    ports:
      - "6380:6379"

volumes:
  pgdata: {}

